# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-14 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dialect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('community', models.CharField(blank=True, choices=[('C', 'Christian'), ('J', 'Jewish')], default='', max_length=1)),
                ('country', models.CharField(blank=True, choices=[('AM', 'Armenia'), ('IR', 'Iran'), ('IQ', 'Iraq'), ('SY', 'Syria'), ('TR', 'Turkey')], default='', max_length=2)),
                ('location', models.CharField(blank=True, choices=[('GEAM', 'Georgia & Armenia'), ('NEIQ', 'NE Iraq'), ('NWIQ', 'NW Iraq'), ('NWIR', 'NW Iran'), ('WIRN', 'W Iran'), ('SETR', 'SE Turkey')], default='', max_length=4)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('source', models.TextField(blank=True)),
                ('information', models.TextField(blank=True)),
                ('remarks', models.TextField(blank=True)),
            ],
        ),
    ]
