# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-25 05:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grammar', '0003_import_headers'),
        ('dialects', '0002_import_dialects'),
    ]

    operations = [
        migrations.CreateModel(
            name='DialectFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('introduction', models.TextField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('dialect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dialects.Dialect')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grammar.Feature')),
            ],
        ),
        migrations.CreateModel(
            name='DialectFeatureEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.CharField(max_length=160)),
                ('frequency', models.CharField(choices=[('P', 'Primary'), ('M', 'Marginal')], default='', max_length=1)),
                ('comment', models.TextField(blank=True, null=True)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dialects.DialectFeature')),
            ],
            options={
                'verbose_name_plural': 'Dialect feature entries',
            },
        ),
        migrations.CreateModel(
            name='DialectFeatureExample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('example', models.CharField(max_length=160)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dialects.DialectFeature')),
            ],
        ),
    ]
