# -*- coding: utf-8 -*-
# gENerated by Django 1.10.1 on 2016-11-29 06:25
from __future__ import unicode_literals
from __future__ import print_function

from django.apps import apps as global_apps
from django.db import migrations
from dialects.models import Dialect, DialectFeature, DialectFeatureExample
from grammar.models import Feature
# removed dependency in 75224e - this migration will not run without it being reinstated
# from legacy.models import GrammarFeatures, GrammarFeatureExamples

def dialect_feature_examples_forward(global_apps, schema_editor):
    for gf in GrammarFeatureExamples.objects.all():
        try:
            f = DialectFeature.objects.get(pk=gf.feature_id)
            df = DialectFeatureExample(
                id=gf.example_id,
                feature=f,
                example=gf.example,
            ).save()
        except:
            print('no feature: ', gf.feature_id)

def dialect_feature_examples_reverse(global_apps, schema_editor):
    try:
        DialectFeatureExample.objects.filter(pk__in=[e.pk for e in GrammarFeatureExamples.objects.all()]).delete()
    except Exception as e:
        print(e)
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('dialects','0005_import_grammar_feature_entries'),
        # removed dependency in 75224e - this migration will not run without it being reinstated
        # ('legacy','0001_initial'),
        ('grammar','0001_initial'),
    ]

    operations = [
        migrations.RunPython(dialect_feature_examples_forward, dialect_feature_examples_reverse),
    ]
