# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-18 05:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dialects', '0006_import_grammar_feature_examples'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dialect',
            options={'ordering': ['name']},
        ),
    ]
