# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-02 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialects', '0007_auto_20180518_0513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialect',
            name='community',
            field=models.CharField(choices=[('C', 'Christian'), ('J', 'Jewish')], default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='dialect',
            name='country',
            field=models.CharField(choices=[('AM', 'Armenia'), ('IR', 'Iran'), ('IQ', 'Iraq'), ('SY', 'Syria'), ('TR', 'Turkey')], default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='dialect',
            name='location',
            field=models.CharField(choices=[('GEAM', 'Georgia & Armenia'), ('NEIQ', 'NE Iraq'), ('NWIQ', 'NW Iraq'), ('NWIR', 'NW Iran'), ('WIRN', 'W Iran'), ('SETR', 'SE Turkey')], default='', max_length=4),
        ),
    ]
