# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-22 11:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dialects', '0009_auto_20180702_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialectfeature',
            name='dialect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='dialects.Dialect'),
        ),
        migrations.AlterField(
            model_name='dialectfeatureentry',
            name='feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='dialects.DialectFeature'),
        ),
        migrations.AlterField(
            model_name='dialectfeatureexample',
            name='feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examples', to='dialects.DialectFeature'),
        ),
    ]
