# Generated by Django 2.1.7 on 2019-03-12 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialects', '0010_auto_20180722_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialectfeature',
            name='category',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='dialectfeature',
            name='is_absent',
            field=models.BooleanField(default=False),
        ),
    ]
