# Generated by Django 2.1.7 on 2019-05-10 14:12
from django.db import migrations

from ftfy import fix_text

from dialects.models import DialectFeatureEntry, DialectFeatureExample


def move_to_entry(dfe):
    entry = DialectFeatureEntry(feature=dfe.feature, entry=dfe.example, frequency='P')
    ## This saving has been switched off as the migration can only be run once
    ## without creating duplicate DialectFeatureEntry's (as it doesn't delete the
    ## source DialectFeatureExample
    #entry.save()
    print('  copying to new DialectFeatureEntry ({})'.format(entry.id))


def forwards(apps, schema_editor):
    print('.')
    dfes = DialectFeatureExample.objects.all()
    for dfe in dfes[0:1]:
        print('{}) {}'.format(dfe.feature.id, dfe))
        move_to_entry(dfe)

def backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('dialects', '0013_clean_dialectfeatures_other'),
    ]

    operations = [
       migrations.RunPython(forwards, backwards),
    ]
