# Generated by Django 3.1.12 on 2022-04-12 15:46

from django.db import migrations, models
import django.db.models.deletion


def add_dialect_groups(apps, schema_editor):
    DialectGroup = apps.get_model('dialects', 'DialectGroup')

    nena_group = DialectGroup(id=1, name='Nena', subdomain='nena',
                              site_title="The North-Eastern Neo-Aramaic Database Project",
                              lead_text="""This website gives access to recordings, transcribed texts and grammatical descriptions of the North Eastern Neo-Aramaic dialects.

Most of these are now highly endangered and some have recently become extinct."""
                             )
    nena_group.save()

    kurdic_group = DialectGroup(id=2, name='Kurdic', subdomain='kurdic',
                              site_title="The Kurdish and Gorani Dialect Database",
                              lead_text=""
                             )
    kurdic_group.save()


class Migration(migrations.Migration):

    dependencies = [
        ('dialects', '0015_dialect_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='DialectGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('subdomain', models.CharField(blank=True, max_length=16, null=True)),
                ('site_title', models.CharField(max_length=50)),
                ('lead_text', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RunPython(code=add_dialect_groups, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='dialect',
            name='community',
            field=models.CharField(choices=[('C', 'Christian'), ('J', 'Jewish'), ('K', 'Kurdish'), ('G', 'Gorani')], default='', max_length=1),
        ),
        migrations.AddField(
            model_name='dialect',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dialects', to='dialects.dialectgroup', default=1),
        ),
        migrations.AlterField( # removes the default=1 which was only needed to mark the existing entries as Nena dialects
            model_name='dialect',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dialects', to='dialects.dialectgroup'),
        ),
    ]
