version: '3'
services:
  app:
    build:
      context: .
    ports:
      - 8000:80
    volumes:
      - ./:/usr/src/app
    environment:
      - DJANGO_READ_DOT_ENV_FILE=True
    env_file:
      - .env
