version: '3'
services:
  app:
    build:
      context: .
    ports:
      - 8000:80
    links:
      - db:db
    volumes:
      - ./:/usr/src/app
    depends_on:
      - db
    environment:
      - DJANGO_DB_HOST=db
      - DJANGO_DB_PORT=3306
      - DJANGO_DB_DEFAULT_USER=root
      - DJANGO_DB_DEFAULT_PASSWORD=
      - GS_PROJECT_ID=
    command: /usr/local/bin/gunicorn --bind=0.0.0.0:80 common.wsgi --reload
  db:
    image: mariadb:10.1
    volumes:
      - ./database:/docker-entrypoint-initdb.d  # Place init .sql file(s) here.
      - mariadb_data_2:/var/lib/mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=True


volumes:
  mariadb_data_2:
    external: true
