version: '3'
services:
  app:
    build:
      context: .
    ports:
      - 8000:80
    links:
      - db:db
    volumes:
      - ./:/usr/src/app
    depends_on:
      - db
    environment:
      - DJANGO_READ_DOT_ENV_FILE=True
    env_file:
      - .env
    command: /usr/local/bin/gunicorn --bind=0.0.0.0:80 common.wsgi --reload
  db:
    image: mariadb:10.1
    ports:
      - 3306
    volumes:
      - ./database:/docker-entrypoint-initdb.d  # Place init .sql file(s) here.
      - mariadb_data:/var/lib/mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=True


volumes:
  mariadb_data:
    external: true
