# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-19 02:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grammar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='fullheading',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True),
        ),
    ]
