# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-18 05:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='original_image',
            field=models.ImageField(upload_to='galleries'),
        ),
    ]
