# Generated by Django 2.1.7 on 2019-03-12 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20180518_0513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='original_image',
            field=models.ImageField(upload_to='photos'),
        ),
    ]
