# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-18 05:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recording',
            name='data',
            field=models.FileField(upload_to='media/'),
        ),
    ]
