# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-18 04:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0002_auto_20180518_0513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recording',
            name='audio',
        ),
        migrations.RemoveField(
            model_name='transcript',
            name='recording',
        ),
        migrations.AddField(
            model_name='audio',
            name='data',
            field=models.FileField(default=None, upload_to='media/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='audio',
            name='transcript',
            field=models.TextField(default='', max_length=78),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='audio',
            name='translation',
            field=models.TextField(default='', max_length=78),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Recording',
        ),
        migrations.DeleteModel(
            name='Transcript',
        ),
    ]
