# Generated by Django 2.1.7 on 2019-03-28 07:48

from django.db import migrations

from ftfy import fix_text

from audio.models import Audio

def forwards(apps, schema_editor):
    audios = Audio.objects.filter(transcript__isnull=False)
    print('.')
    for audio in audios[0:20]:
        print(audio)
        if audio.transcript:
            new_text = fix_text(audio.transcript)
            print('  was: ' + audio.transcript[0:100])
            print('  now: ' + new_text[0:100])
            audio.transcript = new_text
        if audio.translation:
            new_text = fix_text(audio.translation)
            print('  was: ' + audio.translation[0:100])
            print('  now: ' + new_text[0:100])
            audio.translation = new_text

        audio.save()

def backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0006_auto_20190312_0713'),
    ]

    operations = [
       migrations.RunPython(forwards, backwards),
    ]
