# Generated by Django 2.1.7 on 2019-05-07 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0007_clean_transcripts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='transcript',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='audio',
            name='translation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
