# Generated by Django 3.0.5 on 2020-11-11 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0008_auto_20190507_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='place',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='audio',
            name='source',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='audio',
            name='speakers',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='audio',
            name='text_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='audio',
            name='transcriber',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
