# Generated by Django 3.1.8 on 2021-06-09 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0009_auto_20201111_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='nena_file',
            field=models.FileField(blank=True, null=True, upload_to='nenafiles'),
        ),
        migrations.AlterField(
            model_name='audio',
            name='speakers',
            field=models.CharField(blank=True, help_text='Comma-separated list of [Initials]=[Full Name] pairs, eg. "GK=Geoffrey Khan, CK=Cody Kingham"', max_length=200, null=True),
        ),
    ]
