# Generated by Django 3.1.12 on 2022-03-18 14:50

import common.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0010_auto_20210609_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='nena_file',
            field=models.FileField(blank=True, null=True, storage=common.storage_backends.OverwriteStorage(), upload_to='nenafiles'),
        ),
    ]
