# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-18 05:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dialectmaps', '0002_auto_20180518_0529'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dialectmap',
            old_name='title',
            new_name='name',
        ),
    ]
