# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-23 05:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dialects', '0010_auto_20180722_1121'),
        ('dialectmaps', '0003_auto_20180518_0530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapitem',
            name='feature',
        ),
        migrations.AddField(
            model_name='mapitem',
            name='entry',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dialects.DialectFeatureEntry'),
            preserve_default=False,
        ),
    ]
